apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        - name: nginx-html-page1
          mountPath: /usr/share/nginx/html/page1
        - name: nginx-html-page2
          mountPath: /usr/share/nginx/html/page2
        - name: nginx-html-page3
          mountPath: /usr/share/nginx/html/page3
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: nginx-html-page1
        configMap:
          name: nginx-html-page1
      - name: nginx-html-page2
        configMap:
          name: nginx-html-page2
      - name: nginx-html-page3
        configMap:
          name: nginx-html-page3
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
