apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-docs
  template:
    metadata:
      labels:
        app: nginx-docs
    spec:
      containers:
      - name: nginx
        image: sayantoxa/nginx-docs:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-docs-service
spec:
  type: NodePort
  selector:
    app: nginx-docs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80